export default {
    catchSentance: 'reinventing our way of life and changing our vision of habitat',
    inRouteForSelfSufficentHouse: "towards the self-sufficient house",
    weAccompanyEveryoneToTheSelfSufficentHouse: "We accompany those who wish to become self-sufficient in their own house",
    solarPanels: "Photovoltaic panels on flat roofs",
    rainWaterRecuperation:"Rainwater harvesting and filtering",
    permaCulture: "The possibility of having a permaculture garden",
    ourMaterials: 'our materials',
    inOrderToBuildOurHouses: "To build our houses, we opt for a combination of timber-frame and C.L.T. construction.",
    cLT: "In english the cross laminated timber, in french le lamellé de bois croisé, C.L.T. is a set of glued woods, and is very resistant.",
    cltResistance: "Its strength is comparable to that of concrete! Buildings of over 20 floors have been constructed using this technique.",
    constructions: "constructions",
    individualHouses: "individual houses",
    extensions: "extensions",
    cottagesForRent: "cottages for rent",
    renovations: "renovations",
    exteriorFacilities: "exterior facilities",
    permacultureGarden: "permaculture garden",
    poolConstruction: "pool constructions"
}