export default {
    catchSentance: 'réinventons notre mode de vie et faisons évoluer notre vision de l\'habitat',
    inRouteForSelfSufficentHouse: "vers la maison autosuffisante",
    weAccompanyEveryoneToTheSelfSufficentHouse: "Nous accompagnons ceux qui le souhaitent vers la maison autosuffisante",
    solarPanels: "Les panneaux photovoltaïques installés sur les toits terrasses",
    rainWaterRecuperation:"La récuperation et le filtrage de l'eau de pluie",
    permaCulture: "La possibilité d'avoir un jardin en permaculture",
    ourMaterials: 'nos materiaux',
    inOrderToBuildOurHouses: "Pour construire nos maisons, nous optons pour un panachage d'ossature Bois et de C.L.T.",
    cLT: "En anglais le cross laminated timber, en francais le lamellé de bois croisé, le C.L.T est un ensemble de bois collés, et est tres resistant.",
    cltResistance: "Sa resistance est comparable au béton! Il existe des immeubles de plus de 20 étages construits avec cette technique",
    constructions: "constructions",
    individualHouses: "maisons individuelles",
    extensions: "extensions",
    cottagesForRent: "Gites a louer",
    renovations: "renovations",
    exteriorFacilities: "amenagements extérieurs",
    permacultureGarden: "jardin en permaculture",
    poolConstruction: "construction de piscines"
}